BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_customer'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_vehicle'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_station'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_connector'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_tariff'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_session'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_reading'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_ticket'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_session_log'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE seq_customer     START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE seq_vehicle      START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE seq_station      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_connector    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_tariff       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_session      START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE seq_reading      START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE seq_ticket       START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE seq_session_log  START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT === All sequences created successfully ===
-- Purpose: Create sequences for primary-key generation across the schema.
-- Notes: High-volume tables use CACHE for performance; static tables use NOCACHE.
